url: http://moveit_beta.picknik.ai/
plugins:
  - jekyll-feed
  - jekyll-redirect-from

sass:
  style: compressed

#RSS Config

name: MoveIt Motion Planning Framework
description: Incorporating the latest advances in motion planning, manipulation, 3D perception, kinematics, control and navigation.
url: http://moveit_beta.picknik.ai/
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
