name: Build Website

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy-website:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.0'
        bundler-cache: true
    - name: Run .github_actions.sh
      run: NOKOGIRI_USE_SYSTEM_LIBRARIES=true ./.github_actions.sh
